export const SUPABASE_URL = 'https://xkwzpjsbvcilghdsgsld.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrd3pwanNidmNpbGdoZHNnc2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDgyNTksImV4cCI6MjA3MDgyNDI1OX0.YCO3I8oy4iAYEiHt7BYMDhJIodgq3T0mqdMcEszGtvU';
export const BUCKET_NAME = 'taro_image';

export const TAROT_CARD_DEFINITIONS: { name_en: string; name_ko: string }[] = [
  // Major Arcana
  { name_en: "The Fool", name_ko: "바보" },
  { name_en: "The Magician", name_ko: "마법사" },
  { name_en: "The High Priestess", name_ko: "여사제" },
  { name_en: "The Empress", name_ko: "여황제" },
  { name_en: "The Emperor", name_ko: "황제" },
  { name_en: "The Hierophant", name_ko: "교황" },
  { name_en: "The Lovers", name_ko: "연인" },
  { name_en: "The Chariot", name_ko: "전차" },
  { name_en: "Strength", name_ko: "힘" },
  { name_en: "The Hermit", name_ko: "은둔자" },
  { name_en: "Wheel of Fortune", name_ko: "운명의 수레바퀴" },
  { name_en: "Justice", name_ko: "정의" },
  { name_en: "The Hanged Man", name_ko: "매달린 남자" },
  { name_en: "Death", name_ko: "죽음" },
  { name_en: "Temperance", name_ko: "절제" },
  { name_en: "The Devil", name_ko: "악마" },
  { name_en: "The Tower", name_ko: "탑" },
  { name_en: "The Star", name_ko: "별" },
  { name_en: "The Moon", name_ko: "달" },
  { name_en: "The Sun", name_ko: "태양" },
  { name_en: "Judgement", name_ko: "심판" },
  { name_en: "The World", name_ko: "세계" },
  // Wands
  { name_en: "Ace of Wands", name_ko: "완드 에이스" },
  { name_en: "Two of Wands", name_ko: "완드 2" },
  { name_en: "Three of Wands", name_ko: "완드 3" },
  { name_en: "Four of Wands", name_ko: "완드 4" },
  { name_en: "Five of Wands", name_ko: "완드 5" },
  { name_en: "Six of Wands", name_ko: "완드 6" },
  { name_en: "Seven of Wands", name_ko: "완드 7" },
  { name_en: "Eight of Wands", name_ko: "완드 8" },
  { name_en: "Nine of Wands", name_ko: "완드 9" },
  { name_en: "Ten of Wands", name_ko: "완드 10" },
  { name_en: "Page of Wands", name_ko: "완드 페이지" },
  { name_en: "Knight of Wands", name_ko: "완드 나이트" },
  { name_en: "Queen of Wands", name_ko: "완드 퀸" },
  { name_en: "King of Wands", name_ko: "완드 킹" },
  // Cups
  { name_en: "Ace of Cups", name_ko: "컵 에이스" },
  { name_en: "Two of Cups", name_ko: "컵 2" },
  { name_en: "Three of Cups", name_ko: "컵 3" },
  { name_en: "Four of Cups", name_ko: "컵 4" },
  { name_en: "Five of Cups", name_ko: "컵 5" },
  { name_en: "Six of Cups", name_ko: "컵 6" },
  { name_en: "Seven of Cups", name_ko: "컵 7" },
  { name_en: "Eight of Cups", name_ko: "컵 8" },
  { name_en: "Nine of Cups", name_ko: "컵 9" },
  { name_en: "Ten of Cups", name_ko: "컵 10" },
  { name_en: "Page of Cups", name_ko: "컵 페이지" },
  { name_en: "Knight of Cups", name_ko: "컵 나이트" },
  { name_en: "Queen of Cups", name_ko: "컵 퀸" },
  { name_en: "King of Cups", name_ko: "컵 킹" },
  // Swords
  { name_en: "Ace of Swords", name_ko: "소드 에이스" },
  { name_en: "Two of Swords", name_ko: "소드 2" },
  { name_en: "Three of Swords", name_ko: "소드 3" },
  { name_en: "Four of Swords", name_ko: "소드 4" },
  { name_en: "Five of Swords", name_ko: "소드 5" },
  { name_en: "Six of Swords", name_ko: "소드 6" },
  { name_en: "Seven of Swords", name_ko: "소드 7" },
  { name_en: "Eight of Swords", name_ko: "소드 8" },
  { name_en: "Nine of Swords", name_ko: "소드 9" },
  { name_en: "Ten of Swords", name_ko: "소드 10" },
  { name_en: "Page of Swords", name_ko: "소드 페이지" },
  { name_en: "Knight of Swords", name_ko: "소드 나이트" },
  { name_en: "Queen of Swords", name_ko: "소드 퀸" },
  { name_en: "King of Swords", name_ko: "소드 킹" },
  // Pentacles
  { name_en: "Ace of Pentacles", name_ko: "펜타클 에이스" },
  { name_en: "Two of Pentacles", name_ko: "펜타클 2" },
  { name_en: "Three of Pentacles", name_ko: "펜타클 3" },
  { name_en: "Four of Pentacles", name_ko: "펜타클 4" },
  { name_en: "Five of Pentacles", name_ko: "펜타클 5" },
  { name_en: "Six of Pentacles", name_ko: "펜타클 6" },
  { name_en: "Seven of Pentacles", name_ko: "펜타클 7" },
  { name_en: "Eight of Pentacles", name_ko: "펜타클 8" },
  { name_en: "Nine of Pentacles", name_ko: "펜타클 9" },
  { name_en: "Ten of Pentacles", name_ko: "펜타클 10" },
  { name_en: "Page of Pentacles", name_ko: "펜타클 페이지" },
  { name_en: "Knight of Pentacles", name_ko: "펜타클 나이트" },
  { name_en: "Queen of Pentacles", name_ko: "펜타클 퀸" },
  { name_en: "King of Pentacles", name_ko: "펜타클 킹" }
];